// Auto-generated by workers/utils/proxy_builder.py — do not edit by hand.
// Manifest V3 service worker. Two responsibilities:
//   1. Configure Chrome's proxy.settings to route every request via
//      the upstream proxy.
//   2. Answer onAuthRequired with the credentials parsed from the
//      proxy URL. We use the synchronous "blocking" extra info, which
//      MV3 retains support for ONLY when the extension also declares
//      the "webRequestAuthProvider" permission (see manifest above).

const PROXY_CONFIG = {
    mode: "fixed_servers",
    rules: {
        singleProxy: {
            scheme: "http",
            host:   "164.90.193.254",
            port:   10037
        },
        bypassList: ["localhost", "127.0.0.1", "::1"]
    }
};

chrome.proxy.settings.set(
    { value: PROXY_CONFIG, scope: "regular" },
    function () {
        // Setting persists in the profile; nothing to do in the callback.
    }
);

const PROXY_USER = "userrmitv";
const PROXY_PASS = "pjf3j2s3pv9y";

// Synchronous "blocking" listener. MV3 allows this for onAuthRequired
// specifically when "webRequestAuthProvider" is in permissions.
// Returning { authCredentials } tells Chrome to satisfy the proxy's
// HTTP 407 challenge with these creds.
chrome.webRequest.onAuthRequired.addListener(
    function (details) {
        return {
            authCredentials: {
                username: PROXY_USER,
                password: PROXY_PASS
            }
        };
    },
    { urls: ["<all_urls>"] },
    ["blocking"]
);
