#!/usr/bin/env bash
# Interactive .env wizard for absolute beginners.
#
# Asks the 4 questions that must be answered, generates everything else
# automatically (random passwords, secret keys), writes a complete .env file.
#
# Run on the server BEFORE deploy_first_time.sh:
#   sudo bash scripts/init_env.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# ── colours so the prompts look friendly ─────────────────────────────────
if [[ -t 1 ]] && command -v tput >/dev/null 2>&1; then
    BOLD=$(tput bold); DIM=$(tput dim); GREEN=$(tput setaf 2)
    YELLOW=$(tput setaf 3); BLUE=$(tput setaf 4); RESET=$(tput sgr0)
else
    BOLD=""; DIM=""; GREEN=""; YELLOW=""; BLUE=""; RESET=""
fi

echo
echo "${BOLD}${BLUE}╔══════════════════════════════════════════════════════════╗${RESET}"
echo "${BOLD}${BLUE}║  IG_CRM — interactive .env setup wizard                  ║${RESET}"
echo "${BOLD}${BLUE}║  Will ask you 4 things, generate the rest automatically. ║${RESET}"
echo "${BOLD}${BLUE}╚══════════════════════════════════════════════════════════╝${RESET}"
echo

# refuse to silently overwrite an existing .env
if [[ -f .env ]]; then
    echo "${YELLOW}!! .env already exists. Backing it up to .env.backup before overwriting.${RESET}"
    cp .env ".env.backup.$(date +%s)"
fi

# ── Q1: domain ────────────────────────────────────────────────────────────
echo "${BOLD}1/4. Domain${RESET}"
echo "${DIM}This is the address your backend will live at. Must point at THIS server${RESET}"
echo "${DIM}via a DNS A-record. If you don't have one, sign up free at duckdns.org${RESET}"
echo "${DIM}(takes 3 minutes — see DEPLOY.md or ask the chat assistant).${RESET}"
echo
read -rp "  Enter your domain (e.g. ${GREEN}myproject.duckdns.org${RESET}): " DOMAIN
DOMAIN="${DOMAIN// /}"  # strip spaces
if [[ -z "$DOMAIN" || "$DOMAIN" != *.* ]]; then
    echo "${YELLOW}!! Bad domain (must contain a dot). Aborting.${RESET}" >&2
    exit 1
fi
echo "  → ${GREEN}$DOMAIN${RESET}"
echo

# ── Q2: admin email ───────────────────────────────────────────────────────
echo "${BOLD}2/4. Admin email${RESET}"
echo "${DIM}Whichever email you register with in the UI that matches this gets the${RESET}"
echo "${DIM}admin panel. Use a real email — no validation otherwise.${RESET}"
echo
read -rp "  Enter your admin email: " ADMIN_EMAIL
ADMIN_EMAIL="${ADMIN_EMAIL// /}"
if [[ -z "$ADMIN_EMAIL" || "$ADMIN_EMAIL" != *"@"*.* ]]; then
    echo "${YELLOW}!! Bad email. Aborting.${RESET}" >&2
    exit 1
fi
echo "  → ${GREEN}$ADMIN_EMAIL${RESET}"
echo

# ── Q3: OpenAI / Ollama key ───────────────────────────────────────────────
echo "${BOLD}3/4. AI key${RESET}"
echo "${DIM}The default below is the Ollama Cloud permanent key we set up.${RESET}"
echo "${DIM}Press ENTER to keep it, or paste a different key.${RESET}"
echo
DEFAULT_AI_KEY="0d3b420c426e4714a74939f91fcf63cd.EDt3tA0LnXVAMET7P9dgqvpZ"
read -rp "  AI key [${DIM}default Ollama${RESET}]: " AI_KEY
AI_KEY="${AI_KEY:-$DEFAULT_AI_KEY}"
if [[ "$AI_KEY" == "$DEFAULT_AI_KEY" ]]; then
    AI_BASE_URL="https://ollama.com/v1"
    AI_MODEL="gpt-oss:20b"
    echo "  → using ${GREEN}Ollama Cloud${RESET} (gpt-oss:20b)"
else
    # crude provider detection by key prefix
    if [[ "$AI_KEY" == sk-proj-* || "$AI_KEY" == sk-* ]]; then
        AI_BASE_URL="https://api.openai.com/v1"
        AI_MODEL="gpt-4o-mini"
        echo "  → detected ${GREEN}OpenAI${RESET} (gpt-4o-mini)"
    else
        AI_BASE_URL="https://ollama.com/v1"
        AI_MODEL="gpt-oss:20b"
        echo "  → assuming ${GREEN}Ollama${RESET}-style key"
    fi
fi
echo

# ── Q4: CORS / frontend ───────────────────────────────────────────────────
echo "${BOLD}4/4. Frontend origin${RESET}"
echo "${DIM}The URL your Next.js frontend lives at — usually a Vercel link.${RESET}"
echo "${DIM}If you haven't deployed the frontend yet, just press ENTER and we'll${RESET}"
echo "${DIM}use '*' for now (you'll tighten it later in the .env directly).${RESET}"
echo
read -rp "  Frontend URL [${DIM}default *${RESET}]: " FRONTEND_URL
if [[ -z "$FRONTEND_URL" ]]; then
    CORS_ORIGINS='["*"]'
    echo "  → CORS = ${YELLOW}* (any origin — fine for first launch)${RESET}"
else
    FRONTEND_URL="${FRONTEND_URL%/}"   # strip trailing slash
    CORS_ORIGINS="[\"$FRONTEND_URL\"]"
    echo "  → CORS = ${GREEN}$FRONTEND_URL${RESET}"
fi
echo

# ── auto-generate secrets ─────────────────────────────────────────────────
echo "${BOLD}Generating secrets...${RESET}"
SECRET_KEY="$(openssl rand -hex 32)"
PG_PASS="$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)"
echo "  ${GREEN}✓${RESET} SECRET_KEY (Fernet + JWT, never rotate this once set)"
echo "  ${GREEN}✓${RESET} POSTGRES_PASSWORD"
echo

# ── write .env ────────────────────────────────────────────────────────────
cat > .env <<EOF
# Auto-generated by scripts/init_env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Edit by hand only if you know what you're doing.

# ── domain & SSL ──
DOMAIN=$DOMAIN

# ── security ──
SECRET_KEY=$SECRET_KEY
ACCESS_TOKEN_EXPIRE_MINUTES=1440

# ── database ──
POSTGRES_USER=ig_user
POSTGRES_PASSWORD=$PG_PASS
POSTGRES_DB=ig_crm
DATABASE_URL=postgresql+psycopg://ig_user:$PG_PASS@postgres:5432/ig_crm

# ── redis / celery ──
REDIS_URL=redis://redis:6379/0
CELERY_BROKER_URL=redis://redis:6379/1
CELERY_RESULT_BACKEND=redis://redis:6379/2

# ── LLM ──
OPENAI_API_KEY=$AI_KEY
OPENAI_BASE_URL=$AI_BASE_URL
OPENAI_MODEL=$AI_MODEL

# ── admin ──
ADMIN_EMAILS=$ADMIN_EMAIL

# ── CORS ──
CORS_ALLOWED_ORIGINS=$CORS_ORIGINS

# ── browser fleet (sized for 2-core / 8GB VPS) ──
WORKER_CONCURRENCY=2
API_WORKERS=1
AGENTS_FREE=1
AGENTS_PRO=3
AGENTS_ENTERPRISE=5
CAPACITY_CPU_PERCENT=85.0
CAPACITY_RAM_PERCENT=85.0
CAPACITY_MAX_BROWSERS=2

# ── trust gate (0 = accept any proxy; raise to 50 in prod once stable) ──
MIN_TRUST_SCORE=0
ALLOW_NO_PROXY=false

# ── logging ──
LOG_LEVEL=INFO
LOG_DIR=/var/log/ig_crm
LOG_MAX_BYTES=20971520
LOG_BACKUP_COUNT=5

# ── media ──
MEDIA_ROOT=/app/media
FFMPEG_BIN=ffmpeg
FFPROBE_BIN=ffprobe
EOF

chmod 600 .env       # secrets shouldn't be world-readable
echo "${BOLD}${GREEN}✓ Wrote .env (chmod 600)${RESET}"
echo
echo "${BOLD}Next step:${RESET}"
echo "  ${BLUE}sudo bash scripts/deploy_first_time.sh${RESET}"
echo
echo "${DIM}If you ever need to change something later, just edit .env directly:${RESET}"
echo "${DIM}  nano .env${RESET}"
echo "${DIM}  docker compose -f docker-compose.prod.yml restart${RESET}"
